
  CREATE TABLE "PREISDB"."PD_AUSSCHREIBUNG" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"BLOB_ID" NUMBER NOT NULL ENABLE, 
	"MUSTER_ID" NUMBER, 
	"NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"EINHEIT" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"MENGE" NUMBER, 
	"MIN_PREIS" NUMBER, 
	"MITTLERER_PREIS" NUMBER, 
	"MAX_PREIS" NUMBER, 
	"PARENT_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PARENT_NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"MASTER_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"MASTER_NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"KENNUNG" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CODE_COUNT" NUMBER, 
	"MEDIAN_PREIS" NUMBER, 
	"EINZELPREIS" NUMBER, 
	"GESAMTPREIS" NUMBER, 
	"X82" NUMBER, 
	 CONSTRAINT "PD_AUSSCHREIBUNG_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB" ;

   COMMENT ON COLUMN "PREISDB"."PD_AUSSCHREIBUNG"."EINZELPREIS" IS 'nur bei x82';
   COMMENT ON COLUMN "PREISDB"."PD_AUSSCHREIBUNG"."GESAMTPREIS" IS 'nur bei x82';
   COMMENT ON COLUMN "PREISDB"."PD_AUSSCHREIBUNG"."X82" IS '1 = ja';

  CREATE OR REPLACE EDITIONABLE TRIGGER "PREISDB"."PD_AUSSCHREIBUNG_BI_TRG" 
    before insert on PD_AUSSCHREIBUNG
    referencing new as new old as old
    for each row
begin
    IF :NEW.id IS NULL
    THEN
        SELECT PD_AUSSCHREIBUNG_SEQ.NEXTVAL
            INTO :NEW.id
            FROM DUAL;
    END IF;


end;




/
ALTER TRIGGER "PREISDB"."PD_AUSSCHREIBUNG_BI_TRG" ENABLE;


  CREATE TABLE "PREISDB"."PD_MUSTER_LVS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PARENT_ID" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CODE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(1000 BYTE) COLLATE "USING_NLS_COMP", 
	"DESCRIPTION" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"MUSTER_TYP_ID" NUMBER, 
	"POSITION_KENNUNG" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"STAND_DATUM" DATE, 
	"EINHEIT" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"POSITION_KENNUNG2" VARCHAR2(1000 CHAR) COLLATE "USING_NLS_COMP" GENERATED ALWAYS AS (DECODE(INSTR("POSITION_KENNUNG",'ENTS'),0,REPLACE(REPLACE("POSITION_KENNUNG",'-'),'_'),SUBSTR(REPLACE(REPLACE("POSITION_KENNUNG",'-'),'_'),1,LENGTH(REPLACE(REPLACE("POSITION_KENNUNG",'-'),'_'))-1))) VIRTUAL , 
	 CONSTRAINT "PD_MUSTER_LVS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB"  ENABLE, 
	 CONSTRAINT "PD_MUSTER_LVS_FK1" FOREIGN KEY ("MUSTER_TYP_ID")
	  REFERENCES "PREISDB"."PD_IMPORT_TYP" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB" ;

  CREATE BITMAP INDEX "PREISDB"."PD_MUSTER_LVS_IDX1" ON "PREISDB"."PD_MUSTER_LVS" ("POSITION_KENNUNG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB" ;

  CREATE INDEX "PREISDB"."PD_MUSTER_LVS_IDX2" ON "PREISDB"."PD_MUSTER_LVS" (INSTR("POSITION_KENNUNG",'ENTS')) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB" ;

  CREATE INDEX "PREISDB"."PD_MUSTER_LVS_IDX3" ON "PREISDB"."PD_MUSTER_LVS" ("POSITION_KENNUNG2") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PREISDB"."PD_MUSTER_LVS_BIU_TRG" 
    before insert or update on PD_MUSTER_LVS
    referencing new as new old as old
    for each row
begin

    if instr(:NEW.position_kennung,'ENTSS') > 0 then
        --Positionskennung korrigieren: 'ENTSS' -> 'ENTS'
        :NEW.position_kennung := replace(:NEW.position_kennung,'ENTSS','ENTS');
    end if;

end;
/
ALTER TRIGGER "PREISDB"."PD_MUSTER_LVS_BIU_TRG" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PREISDB"."PD_MUSTER_LVS_BI_TRG" 
    before insert on PD_MUSTER_LVS
    referencing new as new old as old
    for each row
begin
    IF :NEW.id IS NULL
    THEN
        SELECT PD_MUSTER_LVS_SEQ.NEXTVAL
            INTO :NEW.id
            FROM DUAL;
    END IF;
end;




/
ALTER TRIGGER "PREISDB"."PD_MUSTER_LVS_BI_TRG" ENABLE;


  CREATE TABLE "PREISDB"."PD_AUFTRAG_POSITIONEN" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"AUFTRAG_ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CODE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"BEZEICHNUNG" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"MENGE" NUMBER, 
	"MENGE_EINHEIT" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"EINHEITSPREIS" NUMBER, 
	"GESAMTBETRAG" NUMBER, 
	"IMPORTIERT_AM" DATE, 
	"IMPORTIERT_VON" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"UMZETZUNG_CODE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"POSITION" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"UMSETZUNG_CODE" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP" GENERATED ALWAYS AS (REPLACE(REPLACE("UMZETZUNG_CODE",'-',''),'_','')) VIRTUAL , 
	 CONSTRAINT "PD_AUFTRAG_POSITIONEN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB"  ENABLE, 
	 CONSTRAINT "PD_AUFTRAG_POSITIONEN_FK1" FOREIGN KEY ("AUFTRAG_ID")
	  REFERENCES "PREISDB"."PD_AUFTRAEGE" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB" ;

  CREATE BITMAP INDEX "PREISDB"."PD_AUFTRAG_POSITION_IDX1" ON "PREISDB"."PD_AUFTRAG_POSITIONEN" ("AUFTRAG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB" ;

  CREATE BITMAP INDEX "PREISDB"."PD_AUFTRAG_POSITION_IDX2" ON "PREISDB"."PD_AUFTRAG_POSITIONEN" ("POSITION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB" ;

  CREATE BITMAP INDEX "PREISDB"."PD_AUFTRAG_POSITION_IDX3" ON "PREISDB"."PD_AUFTRAG_POSITIONEN" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB" ;

  CREATE BITMAP INDEX "PREISDB"."PD_AUFTRAG_POSITION_IDX4" ON "PREISDB"."PD_AUFTRAG_POSITIONEN" ("UMZETZUNG_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB" ;

  CREATE BITMAP INDEX "PREISDB"."PD_AUFTRAG_POSITION_IDX5" ON "PREISDB"."PD_AUFTRAG_POSITIONEN" (REPLACE(REPLACE(REPLACE("UMZETZUNG_CODE",'-'),'_'),' ')) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB" ;

  CREATE INDEX "PREISDB"."PD_AUFTRAG_POSITION_IDX6" ON "PREISDB"."PD_AUFTRAG_POSITIONEN" ("EINHEITSPREIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB" ;

  CREATE INDEX "PREISDB"."PD_AUFTRAG_POSITION_IDX7" ON "PREISDB"."PD_AUFTRAG_POSITIONEN" ("UMSETZUNG_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PREISDB"."PD_AUFTRAG_POSITIONEN_BI_TRG" 
    before insert on "PD_AUFTRAG_POSITIONEN"
    referencing new as new old as old
    for each row
begin
    IF :NEW.id IS NULL
    THEN
        SELECT PD_AUFTRAG_POSITIONEN_SEQ.NEXTVAL
            INTO :NEW.id
            FROM DUAL;
    END IF;

    :NEW.IMPORTIERT_AM := SYSDATE;
    :NEW.IMPORTIERT_VON := v('APP_USER');


end;




/
ALTER TRIGGER "PREISDB"."PD_AUFTRAG_POSITIONEN_BI_TRG" ENABLE;


  CREATE TABLE "PREISDB"."PD_AUFTRAEGE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"AUFTRAGNAHMER_NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"STRASSE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"POSTLEITZAHL" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"STADT" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TELEFON" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"FAX" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"AUFTRAGNAHMER_NAME2" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"PROJEKT_NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"PROJEKT_DESC" VARCHAR2(2000 BYTE) COLLATE "USING_NLS_COMP", 
	"REGIONALBEREICH_ID" NUMBER, 
	"DATUM" DATE, 
	"TOTAL" NUMBER, 
	"KEDITOREN_NUMMER" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"SAP_NR" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"VERTRAG_NR" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"EINLESUNG_STATUS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"DATUM_EINLESUNG" DATE, 
	 CONSTRAINT "PD_AUFTRAGNEHMER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB"  ENABLE, 
	 CONSTRAINT "PD_AUFTRAEGE_FK1" FOREIGN KEY ("REGIONALBEREICH_ID")
	  REFERENCES "PREISDB"."PD_REGION" ("ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB" ;

  CREATE BITMAP INDEX "PREISDB"."PD_AUFTRAEGE_IDX1" ON "PREISDB"."PD_AUFTRAEGE" ("REGIONALBEREICH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB" ;

  CREATE BITMAP INDEX "PREISDB"."PD_AUFTRAEGE_IDX2" ON "PREISDB"."PD_AUFTRAEGE" ("DATUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB" ;

  CREATE BITMAP INDEX "PREISDB"."PD_AUFTRAEGE_IDX3" ON "PREISDB"."PD_AUFTRAEGE" ("KEDITOREN_NUMMER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB" ;

  CREATE BITMAP INDEX "PREISDB"."PD_AUFTRAEGE_IDX4" ON "PREISDB"."PD_AUFTRAEGE" ("EINLESUNG_STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PREISDB"."PD_AUFTRAEGE_BI_TRG" 
    before insert on "PD_AUFTRAEGE"
    referencing new as new old as old
    for each row
begin
    IF :NEW.id IS NULL
    THEN
        SELECT PD_AUFTRAEGE_SEQ.NEXTVAL
            INTO :NEW.id
            FROM DUAL;
    END IF;


end;




/
ALTER TRIGGER "PREISDB"."PD_AUFTRAEGE_BI_TRG" ENABLE;


  CREATE TABLE "PREISDB"."PD_IMPORT_X83" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"MIME_TYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DATEI" BLOB, 
	"DATUM" DATE DEFAULT SYSDATE, 
	"ERSTELLT_BEI" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"IMPORT_TYP" NUMBER, 
	 CONSTRAINT "PD_IMPORT_X83_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB" 
 LOB ("DATEI") STORE AS SECUREFILE (
  TABLESPACE "PREISDB" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "PREISDB"."PD_IMPORT_X83_BI_TRG" 
    before insert on PD_IMPORT_X83
    referencing new as new old as old
    for each row
begin
    IF :NEW.id IS NULL
    THEN
        SELECT PD_IMPORT_X83_SEQ.NEXTVAL
            INTO :NEW.id
            FROM DUAL;
    END IF;
    IF :NEW.DATUM is null then
      :NEW.DATUM := sysdate;
    end if;

end;




/
ALTER TRIGGER "PREISDB"."PD_IMPORT_X83_BI_TRG" ENABLE;


  CREATE TABLE "PREISDB"."PD_IMPORT_X86" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"MIME_TYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DATEI" BLOB, 
	"DATUM" DATE, 
	"ERSTELLT_BEI" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"IMPORT_TYP" NUMBER, 
	"VON" DATE, 
	"BIS" DATE, 
	"GETRIMMTER_MITTELWERT" NUMBER, 
	"REGION" VARCHAR2(1000 CHAR) COLLATE "USING_NLS_COMP", 
	"LVS" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP", 
	"LIEFERANT" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP", 
	"LIEFERANT_LISTE" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP", 
	"VERGABESUMME" NUMBER, 
	"AUSSCHREIBUNG_LV" NUMBER, 
	"VERGABESUMME2" NUMBER, 
	 CONSTRAINT "PD_IMPORT_X86_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PREISDB" 
 LOB ("DATEI") STORE AS SECUREFILE (
  TABLESPACE "PREISDB" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "PREISDB"."PD_IMPORT_X86"."VERGABESUMME" IS 'Filter der Vergaben größer';
   COMMENT ON COLUMN "PREISDB"."PD_IMPORT_X86"."AUSSCHREIBUNG_LV" IS '1=Ja';
   COMMENT ON COLUMN "PREISDB"."PD_IMPORT_X86"."VERGABESUMME2" IS 'Filter der Vergaben kleiner';
   COMMENT ON TABLE "PREISDB"."PD_IMPORT_X86"  IS 'Seite 13';

  CREATE OR REPLACE EDITIONABLE TRIGGER "PREISDB"."PD_IMPORT_X86_BI_TRG" 
    before insert on PD_IMPORT_X86
    referencing new as new old as old
    for each row
begin
    IF :NEW.id IS NULL
    THEN
        SELECT PD_IMPORT_X86_SEQ.NEXTVAL
            INTO :NEW.id
            FROM DUAL;
    END IF;
    IF :NEW.DATUM is null then
      :NEW.DATUM := sysdate;
    end if;

end;




/
ALTER TRIGGER "PREISDB"."PD_IMPORT_X86_BI_TRG" ENABLE;

